name: Radio
version: '1.2'
main: arnett.radio.Radio
api-version: '1.21'

commands:
  fieldradio:
    description: Main command
    aliases: [fieldradio,]
    permission: radio.use
    usage: "Incorrect Usage (/radio <subcommand> ...)"

softdepend: [voicechat]