name: Radio
version: '2.0'
main: arnett.radio.Radio
api-version: '1.21'

commands:
  radiotools:
    description: Main command
    aliases: [r ,rt]
    permission: radio.use
    usage: "Incorrect Usage (/radio <subcommand> ...)"

softdepend: [voicechat]